version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  pgdata:
